# Generated by Django 5.1.5 on 2025-01-20 22:38

from django.db import migrations, models
from linear_regression.models import BeerDrinkers

def seed(*args, **kwargs):
    BeerDrinkers(age = 73, likes_beer = True).save()
    BeerDrinkers(age = 36, likes_beer = False).save()
    BeerDrinkers(age = 8, likes_beer = True).save()
    BeerDrinkers(age = 43, likes_beer = False).save()
    BeerDrinkers(age = 65, likes_beer = False).save()
    BeerDrinkers(age = 91, likes_beer = False).save()
    BeerDrinkers(age = 96, likes_beer = False).save()
    BeerDrinkers(age = 50, likes_beer = True).save()
    BeerDrinkers(age = 84, likes_beer = True).save()
    BeerDrinkers(age = 46, likes_beer = False).save()
    BeerDrinkers(age = 44, likes_beer = False).save()
    BeerDrinkers(age = 55, likes_beer = False).save()
    BeerDrinkers(age = 12, likes_beer = False).save()
    BeerDrinkers(age = 22, likes_beer = True).save()
    BeerDrinkers(age = 88, likes_beer = False).save()
    BeerDrinkers(age = 38, likes_beer = True).save()
    BeerDrinkers(age = 54, likes_beer = True).save()
    BeerDrinkers(age = 99, likes_beer = True).save()
    BeerDrinkers(age = 94, likes_beer = False).save()
    BeerDrinkers(age = 36, likes_beer = True).save()
    BeerDrinkers(age = 37, likes_beer = False).save()
    BeerDrinkers(age = 3, likes_beer = False).save()
    BeerDrinkers(age = 49, likes_beer = True).save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerDrinkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('likes_beer', models.BooleanField()),
            ],
        ),
        migrations.RunPython(seed)
    ]
